### ISSUE TITLE
Error deserializing transaction info

### ISSUE THREAD

**Issue by demogog** [cardano-community/cardanosharp-koios#12]
**Describe the bug**
Using official nuget package fails to deserialise withdrawals part of transaction info with following error:
"The JSON value could not be converted to CardanoSharp.Koios.Sdk.Contracts.TransactionPaymentAddress. Path: $[0].withdrawals[0].stake_addr"

**To Reproduce**
1. Clone repo. 
2. Open solution. 
3. Navigate to  sample project.
4. Change transactionRequest variable to contain only the following hash: "1be5e0c09cb4ff238e00717fcce4f01acc286f7b4595d44334c8b911b6ce600b"
5. Run the project. 
6. transationInformation.Content is null and the transactionInformation.Error is not null, stating deserialisation error

**Expected behavior**
Deserialisation without errors.

**Additional context**
Changing the type of "StakeAddress" in TransactionWithdrawal class from TransactionPaymentAddress to string resolves the issue. 
Like this: 
```
public class TransactionWithdrawal
{
        [DataMember]
        [JsonPropertyName("stake_addr")]
        public string StakeAddress { get; set; }

        [DataMember]
        [JsonPropertyName("amount")]
        public string? Amount { get; set; }
}
```

**Comment by nothingalike** [comment]
@demogog yeah i've been noticing various properties are failling. If you can throw me a PR to resolve this, we can get this fixed sooner.

**Comment by demogog** [comment]
> @demogog yeah i've been noticing various properties are failling. If you can throw me a PR to resolve this, we can get this fixed sooner.

Here you go :) #14

**Comment by nothingalike** [comment]
Resolved with https://github.com/cardano-community/cardanosharp-koios/pull/14
