### ISSUE TITLE
GetBlockList always returns null

### ISSUE THREAD

**Issue by markmihalyi** [cardano-community/cardanosharp-koios#16]
**Describe the bug**
I'm trying to call the GetBlockList function, but `Content` is null all the time.

**To Reproduce**
```
IBlockClient blockClient = RestService.For<IBlockClient>("https://api.koios.rest/api/v0");
ApiResponse<Block[]> blockList = await blockClient.GetBlockList();
Console.WriteLine(blockList.Content == null); // returns True
```

**Comment by safestak-keith** [comment]
Fixed with https://github.com/cardano-community/cardanosharp-koios/pull/19 and new package released at https://www.nuget.org/packages/CardanoSharp.Koios.Client/1.0.8
