### ISSUE TITLE
Returning 404s for Resources accepting Request Body arrays

### ISSUE THREAD

**Issue by safestak-keith** [cardano-community/cardanosharp-koios#18]
**Describe the bug**
SDK is now returning 404s for Resources accepting Request Body JSON arrays, (e.g. `_stake_addresses` and `_addresses`) which were previously query string parameters accepting a single value. 

**To Reproduce**
Execute any of the following statements
```
var accountInfo = await accountClient.GetStakeInformation(stakeAddress.ToString()).ConfigureAwait(false);
var assets = await accountClient.GetStakeAssets(stakeAddress.ToString()).ConfigureAwait(false);
var addressInfo = (await addressClient.GetAddressInformation(address.ToString()).ConfigureAwait(false));
```

**Expected behavior**
A valid response status code and body.

**Additional context**
First discovered from issue https://github.com/CardanoSharp/cscli/issues/12

**Comment by rdlrt** [comment]
Perhaps would be good to map out the koios version support as well with the SDK, as that'd very specifically clarify what versions the SDK supports until, and gives good baseline on progress?

**Comment by safestak-keith** [comment]
I love the idea of synchronising the major and minor parts but the big gap between [CardanoSharp.Koios.Sdk (v6.0.0)](https://www.nuget.org/packages/CardanoSharp.Koios.Sdk/#versions-body-tab) and gRest (v1.0.8) with existing consumers involved make it rather tricky. For now, the safest approach for existing consumers appears to be through documentation, i.e. making the specific gRest version abundantly clear in the repo and package manager docs. 

@nothingalike Perhaps we can publish a brand new package under a different nuget id, e.g. `CardanoSharp.Koios.Client` and start using v1.0.8. @rdlrt It will also make our lives much easier if there is strict semantic versioning in place for any future changes.

I will try my best to raise a PR soon to synchronise this SDK to v1.0.8 but this looks to be quite a chunky one since quite a lot has changed.

**Comment by nothingalike** [comment]
> @nothingalike Perhaps we can publish a brand new package under a different nuget id, e.g. CardanoSharp.Koios.Client and start using v1.0.8. @rdlrt It will also make our lives much easier if there is strict semantic versioning in place for any future changes.

I think this is a good idea

**Comment by safestak-keith** [comment]
Fixed with https://github.com/cardano-community/cardanosharp-koios/pull/19 and new package released at https://www.nuget.org/packages/CardanoSharp.Koios.Client/1.0.8
