### ISSUE TITLE
Support for PostgREST filters

### ISSUE THREAD

**Issue by rdlrt** [cardano-community/cardanosharp-koios#2]
Would be good to be able to use filters, sorting, orders, etc that PostgREST provides OOTB (see documentation [here](https://api.koios.rest/#overview--api-usage) )

**Comment by nothingalike** [comment]
## PR 10 - Api Response Update
https://github.com/cardano-community/cardanosharp-koios/pull/10

This PR will introduce limit, offset, and response headers. 

---------------------------

### Filtering 
Will need to be specific to each endpoint. PRs welcome from anyone able to add a few optional parameters.

### Ordering and Sorting
This will be the same update to all endpoints to accept these optional parameters.

**Comment by robinboening** [comment]
#10 has been merged. I think this issue could be closed.
